// Code generated by MockGen. DO NOT EDIT.
// Source: search/core/ports.go
//
// Generated by this command:
//
//	mockgen -source=search/core/ports.go -destination=search/core/mocks/ports_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	core "yadro.com/course/search/core"
)

// MockSearcher is a mock of Searcher interface.
type MockSearcher struct {
	ctrl     *gomock.Controller
	recorder *MockSearcherMockRecorder
	isgomock struct{}
}

// MockSearcherMockRecorder is the mock recorder for MockSearcher.
type MockSearcherMockRecorder struct {
	mock *MockSearcher
}

// NewMockSearcher creates a new mock instance.
func NewMockSearcher(ctrl *gomock.Controller) *MockSearcher {
	mock := &MockSearcher{ctrl: ctrl}
	mock.recorder = &MockSearcherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSearcher) EXPECT() *MockSearcherMockRecorder {
	return m.recorder
}

// GetComics mocks base method.
func (m *MockSearcher) GetComics(ctx context.Context, comicsID int) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetComics", ctx, comicsID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetComics indicates an expected call of GetComics.
func (mr *MockSearcherMockRecorder) GetComics(ctx, comicsID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetComics", reflect.TypeOf((*MockSearcher)(nil).GetComics), ctx, comicsID)
}

// ISearch mocks base method.
func (m *MockSearcher) ISearch(ctx context.Context, phrase string, limit int) ([]core.ImageInformation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ISearch", ctx, phrase, limit)
	ret0, _ := ret[0].([]core.ImageInformation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ISearch indicates an expected call of ISearch.
func (mr *MockSearcherMockRecorder) ISearch(ctx, phrase, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ISearch", reflect.TypeOf((*MockSearcher)(nil).ISearch), ctx, phrase, limit)
}

// Search mocks base method.
func (m *MockSearcher) Search(ctx context.Context, phrase string, limit int) ([]core.ImageInformation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Search", ctx, phrase, limit)
	ret0, _ := ret[0].([]core.ImageInformation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Search indicates an expected call of Search.
func (mr *MockSearcherMockRecorder) Search(ctx, phrase, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Search", reflect.TypeOf((*MockSearcher)(nil).Search), ctx, phrase, limit)
}

// MockWords is a mock of Words interface.
type MockWords struct {
	ctrl     *gomock.Controller
	recorder *MockWordsMockRecorder
	isgomock struct{}
}

// MockWordsMockRecorder is the mock recorder for MockWords.
type MockWordsMockRecorder struct {
	mock *MockWords
}

// NewMockWords creates a new mock instance.
func NewMockWords(ctrl *gomock.Controller) *MockWords {
	mock := &MockWords{ctrl: ctrl}
	mock.recorder = &MockWordsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWords) EXPECT() *MockWordsMockRecorder {
	return m.recorder
}

// Norm mocks base method.
func (m *MockWords) Norm(ctx context.Context, phrase string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Norm", ctx, phrase)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Norm indicates an expected call of Norm.
func (mr *MockWordsMockRecorder) Norm(ctx, phrase any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Norm", reflect.TypeOf((*MockWords)(nil).Norm), ctx, phrase)
}

// MockDB is a mock of DB interface.
type MockDB struct {
	ctrl     *gomock.Controller
	recorder *MockDBMockRecorder
	isgomock struct{}
}

// MockDBMockRecorder is the mock recorder for MockDB.
type MockDBMockRecorder struct {
	mock *MockDB
}

// NewMockDB creates a new mock instance.
func NewMockDB(ctrl *gomock.Controller) *MockDB {
	mock := &MockDB{ctrl: ctrl}
	mock.recorder = &MockDBMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDB) EXPECT() *MockDBMockRecorder {
	return m.recorder
}

// CreateIndex mocks base method.
func (m *MockDB) CreateIndex() ([]core.WordInformation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateIndex")
	ret0, _ := ret[0].([]core.WordInformation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateIndex indicates an expected call of CreateIndex.
func (mr *MockDBMockRecorder) CreateIndex() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateIndex", reflect.TypeOf((*MockDB)(nil).CreateIndex))
}

// GetComics mocks base method.
func (m *MockDB) GetComics(ctx context.Context, comicsID int) (core.ImageInformation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetComics", ctx, comicsID)
	ret0, _ := ret[0].(core.ImageInformation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetComics indicates an expected call of GetComics.
func (mr *MockDBMockRecorder) GetComics(ctx, comicsID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetComics", reflect.TypeOf((*MockDB)(nil).GetComics), ctx, comicsID)
}

// Search mocks base method.
func (m *MockDB) Search(ctx context.Context, words []string) ([]core.ImageInformation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Search", ctx, words)
	ret0, _ := ret[0].([]core.ImageInformation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Search indicates an expected call of Search.
func (mr *MockDBMockRecorder) Search(ctx, words any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Search", reflect.TypeOf((*MockDB)(nil).Search), ctx, words)
}

// MockInMemoryRep is a mock of InMemoryRep interface.
type MockInMemoryRep struct {
	ctrl     *gomock.Controller
	recorder *MockInMemoryRepMockRecorder
	isgomock struct{}
}

// MockInMemoryRepMockRecorder is the mock recorder for MockInMemoryRep.
type MockInMemoryRepMockRecorder struct {
	mock *MockInMemoryRep
}

// NewMockInMemoryRep creates a new mock instance.
func NewMockInMemoryRep(ctrl *gomock.Controller) *MockInMemoryRep {
	mock := &MockInMemoryRep{ctrl: ctrl}
	mock.recorder = &MockInMemoryRepMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInMemoryRep) EXPECT() *MockInMemoryRepMockRecorder {
	return m.recorder
}

// DeleteIndex mocks base method.
func (m *MockInMemoryRep) DeleteIndex() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "DeleteIndex")
}

// DeleteIndex indicates an expected call of DeleteIndex.
func (mr *MockInMemoryRepMockRecorder) DeleteIndex() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteIndex", reflect.TypeOf((*MockInMemoryRep)(nil).DeleteIndex))
}

// RebuildIndex mocks base method.
func (m *MockInMemoryRep) RebuildIndex(rep map[string][]core.ImageInformation) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RebuildIndex", rep)
	ret0, _ := ret[0].(error)
	return ret0
}

// RebuildIndex indicates an expected call of RebuildIndex.
func (mr *MockInMemoryRepMockRecorder) RebuildIndex(rep any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RebuildIndex", reflect.TypeOf((*MockInMemoryRep)(nil).RebuildIndex), rep)
}

// Search mocks base method.
func (m *MockInMemoryRep) Search(ctx context.Context, words []string) ([]core.QuantityComics, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Search", ctx, words)
	ret0, _ := ret[0].([]core.QuantityComics)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Search indicates an expected call of Search.
func (mr *MockInMemoryRepMockRecorder) Search(ctx, words any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Search", reflect.TypeOf((*MockInMemoryRep)(nil).Search), ctx, words)
}
