// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/folders/folders.proto

package folders

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateFolderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateFolderRequest) Reset() {
	*x = CreateFolderRequest{}
	mi := &file_proto_folders_folders_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFolderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFolderRequest) ProtoMessage() {}

func (x *CreateFolderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_folders_folders_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFolderRequest.ProtoReflect.Descriptor instead.
func (*CreateFolderRequest) Descriptor() ([]byte, []int) {
	return file_proto_folders_folders_proto_rawDescGZIP(), []int{0}
}

func (x *CreateFolderRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateFolderRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateFolderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FolderId      int64                  `protobuf:"varint,1,opt,name=folder_id,json=folderId,proto3" json:"folder_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateFolderResponse) Reset() {
	*x = CreateFolderResponse{}
	mi := &file_proto_folders_folders_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFolderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFolderResponse) ProtoMessage() {}

func (x *CreateFolderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_folders_folders_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFolderResponse.ProtoReflect.Descriptor instead.
func (*CreateFolderResponse) Descriptor() ([]byte, []int) {
	return file_proto_folders_folders_proto_rawDescGZIP(), []int{1}
}

func (x *CreateFolderResponse) GetFolderId() int64 {
	if x != nil {
		return x.FolderId
	}
	return 0
}

type DeleteFolderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FolderId      int64                  `protobuf:"varint,2,opt,name=folder_id,json=folderId,proto3" json:"folder_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFolderRequest) Reset() {
	*x = DeleteFolderRequest{}
	mi := &file_proto_folders_folders_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFolderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFolderRequest) ProtoMessage() {}

func (x *DeleteFolderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_folders_folders_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFolderRequest.ProtoReflect.Descriptor instead.
func (*DeleteFolderRequest) Descriptor() ([]byte, []int) {
	return file_proto_folders_folders_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteFolderRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *DeleteFolderRequest) GetFolderId() int64 {
	if x != nil {
		return x.FolderId
	}
	return 0
}

type AddComicsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FolderId      int64                  `protobuf:"varint,2,opt,name=folder_id,json=folderId,proto3" json:"folder_id,omitempty"`
	ComicsId      int64                  `protobuf:"varint,3,opt,name=comics_id,json=comicsId,proto3" json:"comics_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddComicsRequest) Reset() {
	*x = AddComicsRequest{}
	mi := &file_proto_folders_folders_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddComicsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddComicsRequest) ProtoMessage() {}

func (x *AddComicsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_folders_folders_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddComicsRequest.ProtoReflect.Descriptor instead.
func (*AddComicsRequest) Descriptor() ([]byte, []int) {
	return file_proto_folders_folders_proto_rawDescGZIP(), []int{3}
}

func (x *AddComicsRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AddComicsRequest) GetFolderId() int64 {
	if x != nil {
		return x.FolderId
	}
	return 0
}

func (x *AddComicsRequest) GetComicsId() int64 {
	if x != nil {
		return x.ComicsId
	}
	return 0
}

type DeleteComicsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FolderId      int64                  `protobuf:"varint,2,opt,name=folder_id,json=folderId,proto3" json:"folder_id,omitempty"`
	ComicsId      int64                  `protobuf:"varint,3,opt,name=comics_id,json=comicsId,proto3" json:"comics_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteComicsRequest) Reset() {
	*x = DeleteComicsRequest{}
	mi := &file_proto_folders_folders_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteComicsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteComicsRequest) ProtoMessage() {}

func (x *DeleteComicsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_folders_folders_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteComicsRequest.ProtoReflect.Descriptor instead.
func (*DeleteComicsRequest) Descriptor() ([]byte, []int) {
	return file_proto_folders_folders_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteComicsRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *DeleteComicsRequest) GetFolderId() int64 {
	if x != nil {
		return x.FolderId
	}
	return 0
}

func (x *DeleteComicsRequest) GetComicsId() int64 {
	if x != nil {
		return x.ComicsId
	}
	return 0
}

type ListComicsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FolderId      int64                  `protobuf:"varint,2,opt,name=folder_id,json=folderId,proto3" json:"folder_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListComicsRequest) Reset() {
	*x = ListComicsRequest{}
	mi := &file_proto_folders_folders_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListComicsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListComicsRequest) ProtoMessage() {}

func (x *ListComicsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_folders_folders_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListComicsRequest.ProtoReflect.Descriptor instead.
func (*ListComicsRequest) Descriptor() ([]byte, []int) {
	return file_proto_folders_folders_proto_rawDescGZIP(), []int{5}
}

func (x *ListComicsRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ListComicsRequest) GetFolderId() int64 {
	if x != nil {
		return x.FolderId
	}
	return 0
}

type Comics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ComicsId      int64                  `protobuf:"varint,1,opt,name=comics_id,json=comicsId,proto3" json:"comics_id,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Comics) Reset() {
	*x = Comics{}
	mi := &file_proto_folders_folders_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Comics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Comics) ProtoMessage() {}

func (x *Comics) ProtoReflect() protoreflect.Message {
	mi := &file_proto_folders_folders_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Comics.ProtoReflect.Descriptor instead.
func (*Comics) Descriptor() ([]byte, []int) {
	return file_proto_folders_folders_proto_rawDescGZIP(), []int{6}
}

func (x *Comics) GetComicsId() int64 {
	if x != nil {
		return x.ComicsId
	}
	return 0
}

func (x *Comics) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type ListComicsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Comics        []*Comics              `protobuf:"bytes,1,rep,name=comics,proto3" json:"comics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListComicsResponse) Reset() {
	*x = ListComicsResponse{}
	mi := &file_proto_folders_folders_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListComicsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListComicsResponse) ProtoMessage() {}

func (x *ListComicsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_folders_folders_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListComicsResponse.ProtoReflect.Descriptor instead.
func (*ListComicsResponse) Descriptor() ([]byte, []int) {
	return file_proto_folders_folders_proto_rawDescGZIP(), []int{7}
}

func (x *ListComicsResponse) GetComics() []*Comics {
	if x != nil {
		return x.Comics
	}
	return nil
}

type ListFoldersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFoldersRequest) Reset() {
	*x = ListFoldersRequest{}
	mi := &file_proto_folders_folders_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFoldersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFoldersRequest) ProtoMessage() {}

func (x *ListFoldersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_folders_folders_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFoldersRequest.ProtoReflect.Descriptor instead.
func (*ListFoldersRequest) Descriptor() ([]byte, []int) {
	return file_proto_folders_folders_proto_rawDescGZIP(), []int{8}
}

func (x *ListFoldersRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type Folder struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FolderId      int64                  `protobuf:"varint,1,opt,name=folder_id,json=folderId,proto3" json:"folder_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Folder) Reset() {
	*x = Folder{}
	mi := &file_proto_folders_folders_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Folder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Folder) ProtoMessage() {}

func (x *Folder) ProtoReflect() protoreflect.Message {
	mi := &file_proto_folders_folders_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Folder.ProtoReflect.Descriptor instead.
func (*Folder) Descriptor() ([]byte, []int) {
	return file_proto_folders_folders_proto_rawDescGZIP(), []int{9}
}

func (x *Folder) GetFolderId() int64 {
	if x != nil {
		return x.FolderId
	}
	return 0
}

func (x *Folder) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ListFoldersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Folders       []*Folder              `protobuf:"bytes,1,rep,name=folders,proto3" json:"folders,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFoldersResponse) Reset() {
	*x = ListFoldersResponse{}
	mi := &file_proto_folders_folders_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFoldersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFoldersResponse) ProtoMessage() {}

func (x *ListFoldersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_folders_folders_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFoldersResponse.ProtoReflect.Descriptor instead.
func (*ListFoldersResponse) Descriptor() ([]byte, []int) {
	return file_proto_folders_folders_proto_rawDescGZIP(), []int{10}
}

func (x *ListFoldersResponse) GetFolders() []*Folder {
	if x != nil {
		return x.Folders
	}
	return nil
}

var File_proto_folders_folders_proto protoreflect.FileDescriptor

const file_proto_folders_folders_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/folders/folders.proto\x12\afolders\x1a\x1bgoogle/protobuf/empty.proto\"B\n" +
	"\x13CreateFolderRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"3\n" +
	"\x14CreateFolderResponse\x12\x1b\n" +
	"\tfolder_id\x18\x01 \x01(\x03R\bfolderId\"K\n" +
	"\x13DeleteFolderRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1b\n" +
	"\tfolder_id\x18\x02 \x01(\x03R\bfolderId\"e\n" +
	"\x10AddComicsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1b\n" +
	"\tfolder_id\x18\x02 \x01(\x03R\bfolderId\x12\x1b\n" +
	"\tcomics_id\x18\x03 \x01(\x03R\bcomicsId\"h\n" +
	"\x13DeleteComicsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1b\n" +
	"\tfolder_id\x18\x02 \x01(\x03R\bfolderId\x12\x1b\n" +
	"\tcomics_id\x18\x03 \x01(\x03R\bcomicsId\"I\n" +
	"\x11ListComicsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1b\n" +
	"\tfolder_id\x18\x02 \x01(\x03R\bfolderId\"7\n" +
	"\x06Comics\x12\x1b\n" +
	"\tcomics_id\x18\x01 \x01(\x03R\bcomicsId\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\"=\n" +
	"\x12ListComicsResponse\x12'\n" +
	"\x06comics\x18\x01 \x03(\v2\x0f.folders.ComicsR\x06comics\"-\n" +
	"\x12ListFoldersRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"9\n" +
	"\x06Folder\x12\x1b\n" +
	"\tfolder_id\x18\x01 \x01(\x03R\bfolderId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"@\n" +
	"\x13ListFoldersResponse\x12)\n" +
	"\afolders\x18\x01 \x03(\v2\x0f.folders.FolderR\afolders2\xb3\x03\n" +
	"\aFolders\x12K\n" +
	"\fCreateFolder\x12\x1c.folders.CreateFolderRequest\x1a\x1d.folders.CreateFolderResponse\x12D\n" +
	"\fDeleteFolder\x12\x1c.folders.DeleteFolderRequest\x1a\x16.google.protobuf.Empty\x12>\n" +
	"\tAddComics\x12\x19.folders.AddComicsRequest\x1a\x16.google.protobuf.Empty\x12D\n" +
	"\fDeleteComics\x12\x1c.folders.DeleteComicsRequest\x1a\x16.google.protobuf.Empty\x12E\n" +
	"\n" +
	"ListComics\x12\x1a.folders.ListComicsRequest\x1a\x1b.folders.ListComicsResponse\x12H\n" +
	"\vListFolders\x12\x1b.folders.ListFoldersRequest\x1a\x1c.folders.ListFoldersResponseB Z\x1eyadro.com/course/proto/foldersb\x06proto3"

var (
	file_proto_folders_folders_proto_rawDescOnce sync.Once
	file_proto_folders_folders_proto_rawDescData []byte
)

func file_proto_folders_folders_proto_rawDescGZIP() []byte {
	file_proto_folders_folders_proto_rawDescOnce.Do(func() {
		file_proto_folders_folders_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_folders_folders_proto_rawDesc), len(file_proto_folders_folders_proto_rawDesc)))
	})
	return file_proto_folders_folders_proto_rawDescData
}

var file_proto_folders_folders_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_folders_folders_proto_goTypes = []any{
	(*CreateFolderRequest)(nil),  // 0: folders.CreateFolderRequest
	(*CreateFolderResponse)(nil), // 1: folders.CreateFolderResponse
	(*DeleteFolderRequest)(nil),  // 2: folders.DeleteFolderRequest
	(*AddComicsRequest)(nil),     // 3: folders.AddComicsRequest
	(*DeleteComicsRequest)(nil),  // 4: folders.DeleteComicsRequest
	(*ListComicsRequest)(nil),    // 5: folders.ListComicsRequest
	(*Comics)(nil),               // 6: folders.Comics
	(*ListComicsResponse)(nil),   // 7: folders.ListComicsResponse
	(*ListFoldersRequest)(nil),   // 8: folders.ListFoldersRequest
	(*Folder)(nil),               // 9: folders.Folder
	(*ListFoldersResponse)(nil),  // 10: folders.ListFoldersResponse
	(*emptypb.Empty)(nil),        // 11: google.protobuf.Empty
}
var file_proto_folders_folders_proto_depIdxs = []int32{
	6,  // 0: folders.ListComicsResponse.comics:type_name -> folders.Comics
	9,  // 1: folders.ListFoldersResponse.folders:type_name -> folders.Folder
	0,  // 2: folders.Folders.CreateFolder:input_type -> folders.CreateFolderRequest
	2,  // 3: folders.Folders.DeleteFolder:input_type -> folders.DeleteFolderRequest
	3,  // 4: folders.Folders.AddComics:input_type -> folders.AddComicsRequest
	4,  // 5: folders.Folders.DeleteComics:input_type -> folders.DeleteComicsRequest
	5,  // 6: folders.Folders.ListComics:input_type -> folders.ListComicsRequest
	8,  // 7: folders.Folders.ListFolders:input_type -> folders.ListFoldersRequest
	1,  // 8: folders.Folders.CreateFolder:output_type -> folders.CreateFolderResponse
	11, // 9: folders.Folders.DeleteFolder:output_type -> google.protobuf.Empty
	11, // 10: folders.Folders.AddComics:output_type -> google.protobuf.Empty
	11, // 11: folders.Folders.DeleteComics:output_type -> google.protobuf.Empty
	7,  // 12: folders.Folders.ListComics:output_type -> folders.ListComicsResponse
	10, // 13: folders.Folders.ListFolders:output_type -> folders.ListFoldersResponse
	8,  // [8:14] is the sub-list for method output_type
	2,  // [2:8] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_proto_folders_folders_proto_init() }
func file_proto_folders_folders_proto_init() {
	if File_proto_folders_folders_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_folders_folders_proto_rawDesc), len(file_proto_folders_folders_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_folders_folders_proto_goTypes,
		DependencyIndexes: file_proto_folders_folders_proto_depIdxs,
		MessageInfos:      file_proto_folders_folders_proto_msgTypes,
	}.Build()
	File_proto_folders_folders_proto = out.File
	file_proto_folders_folders_proto_goTypes = nil
	file_proto_folders_folders_proto_depIdxs = nil
}
